### ISSUE TITLE
Migration from `linuxserver/transmission`?

### ISSUE THREAD

**Issue by axiopaladin** [Relativ-IT/TransmissionBT#1]
It would be handy to have some docs on how to switch from the other popular docker image for transmission (`lscr.io/linuxserver/transmission`) to this one. I wanted to switch to this, as lscr.io doesn't offer an up-to-date nightly/weekly build like this one's `main` tag. I tried just swapping them out (and changing the `/downloads` to `/download`) in my compose file, but it threw errors on all the torrents I had from previously, even if I tried "verify local data", and I wasn't able to troubleshoot what was wrong---nothing came up in `docker logs`.

Some brief guidance on (what I assume is) a pretty common use-case would be appreciated, whether it's here or on [DockerHub](https://hub.docker.com/r/nemric/transmission) :)

**Comment by Nemric** [comment]
Hi,
Indeed, docs are quite empty ^^ sorry for that.
I did check linuxserver conf and everything looks the same except the UID and GID
Perhaps could you add the docker command `--user=1000:1000` to use same user
